<a href="https://colab.research.google.com/github/Priyankabalumuri/690/blob/main/assignments_06/assignment_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment 06
### Note:
- For visualization, you should use Plotly Express 
- Use this notebook as your template and follow the instructions

The first half of this assignment is similar to assignment 04.

This gives you a chance to refresh.

The second half is new and gives you a chance to perform additional practices.

You also get a chance to use some of the Python libraries and techniques.

The links to the zip file is:

- https://collegescorecard.ed.gov/data (This web page contains the link to the zip file)

- https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip (The link to the zip file)

You can run `!wget` command in Colab notebook to retrieve it directly, then run `!unzip` command to extract files (I have provided the cells to do so next for your convenience)

Your folder structure should look like this in your Colab enviroment:

- ...
- 'MERGED1996_97_PP.csv',
- 'MERGED2015_16_PP.csv',
- ...
- 'MERGED2017_18_PP.csv'
- ...

**Note: you should refresh the folder to see all files.**

## Step 1 - Retrieve the zip file

In [1]:
!wget https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip

--2022-10-10 01:30:28--  https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip
Resolving ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)... 3.30.138.208, 3.30.49.38, 2600:1f12:18a:7d00:35c5:2f94:bca6:6240, ...
Connecting to ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)|3.30.138.208|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 410294884 (391M) [application/zip]
Saving to: ‘CollegeScorecard_Raw_Data_09012022.zip’

CollegeScorecard_Ra 100%[===================>] 391.29M  61.5MB/s    in 6.4s

2022-10-10 01:30:35 (61.5 MB/s) - ‘CollegeScorecard_Raw_Data_09012022.zip’ saved [410294884/410294884]

## Step 2 - Unzip the zip file

In [2]:
!unzip CollegeScorecard_Raw_Data_09012022.zip

Archive:  CollegeScorecard_Raw_Data_09012022.zip
 extracting: Crosswalks.zip
  inflating: data.yaml
  inflating: FieldOfStudyData1415_1516_PP.csv
  inflating: FieldOfStudyData1516_1617_PP.csv
  inflating: FieldOfStudyData1617_1718_PP.csv
  inflating: FieldOfStudyData1718_1819_PP.csv
  inflating: MERGED1996_97_PP.csv
  inflating: MERGED1997_98_PP.csv
  inflating: MERGED1998_99_PP.csv
  inflating: MERGED1999_00_PP.csv
  inflating: MERGED2000_01_PP.csv
  inflating: MERGED2001_02_PP.csv
  inflating: MERGED2002_03_PP.csv
  inflating: MERGED2003_04_PP.csv
  inflating: MERGED2004_05_PP.csv
  inflating: MERGED2005_06_PP.csv
  inflating: MERGED2006_07_PP.csv
  inflating: MERGED2007_08_PP.csv
  inflating: MERGED2008_09_PP.csv
  inflating: MERGED2009_10_PP.csv
  inflating: MERGED2010_11_PP.csv
  inflating: MERGED2011_12_PP.csv
  inflating: MERGED2012_13_PP.csv
  inflating: MERGED2013_14_PP.csv
  inflating: MERGED2014_15_PP.csv
  inflating: MERGED2015_16_PP.csv
  inflating: MERGED2016_17_PP.csv
  inflating: MERGED2017_18_PP.csv
  inflating: MERGED2018_19_PP.csv
  inflating: MERGED2019_20_PP.csv
  inflating: MERGED2020_21_PP.csv
  inflating: Most-Recent-Cohorts-Field-of-Study.csv
  inflating: Most-Recent-Cohorts-Institution.csv

## Step 3 - Import Libraries

In [3]:
#(Write code below)
import pandas as pd
import os

In [7]:
import numpy as np
import glob
import plotly.express as px

## Step 4 - Display the current working directory using os.getcwd()

You would need to import a standard Python library called os which stands for operating system. so place that import statement in the previous cell. Since your notebook and your data files may or may not in the same folder, you want to make sure what the current working folder is and how to access a data file in a different folder.

In [8]:
#(Write code below)
os.getcwd()

'/content'

## Step 5 - Get the list of file names

os library has a method call listdir which generates a list of files in a directory/folder. Use this method to assign the contents (list of file names) of the data folder to a variable and display it. If necessary, you can use ../ construct to traverse to the parent folder and then to another foloder parallel to the current folder

In [9]:
#(Write code below)
name_list = os.listdir()
name_list

['.config',
 'MERGED2006_07_PP.csv',
 'MERGED2009_10_PP.csv',
 'MERGED2003_04_PP.csv',
 'MERGED1998_99_PP.csv',
 'Crosswalks.zip',
 'MERGED2012_13_PP.csv',
 'MERGED2019_20_PP.csv',
 'MERGED2011_12_PP.csv',
 'MERGED2014_15_PP.csv',
 'Most-Recent-Cohorts-Field-of-Study.csv',
 'MERGED2000_01_PP.csv',
 'MERGED2007_08_PP.csv',
 'MERGED2016_17_PP.csv',
 'FieldOfStudyData1718_1819_PP.csv',
 'MERGED2018_19_PP.csv',
 'MERGED2008_09_PP.csv',
 'MERGED2002_03_PP.csv',
 'MERGED2004_05_PP.csv',
 'MERGED2010_11_PP.csv',
 'MERGED2013_14_PP.csv',
 'MERGED2005_06_PP.csv',
 'FieldOfStudyData1516_1617_PP.csv',
 'MERGED1999_00_PP.csv',
 'MERGED2015_16_PP.csv',
 'MERGED1996_97_PP.csv',
 'FieldOfStudyData1415_1516_PP.csv',
 'FieldOfStudyData1617_1718_PP.csv',
 'MERGED2017_18_PP.csv',
 'data.yaml',
 'Most-Recent-Cohorts-Institution.csv',
 'MERGED1997_98_PP.csv',
 'MERGED2020_21_PP.csv',
 'CollegeScorecard_Raw_Data_09012022.zip',
 'MERGED2001_02_PP.csv',
 'sample_data']

## Step 6 - Process only the yearly data files

The folder contains files that are not the yearly data files. Write code to remove the unwanted files from the list variable.

Note: don't remove/delete these files from the folder in the folder.
For example, use the file extension to only use the csv files or use the name patter - data file name begins with "MERGED". You can use the concept of list comprehension to write just *one* line of code as well as using a for loop, your choice.

In [14]:
#(Write code below)
yearly_list = [file_name for file_name in name_list if file_name.startswith("MERGED")]

yearly_list

['MERGED2006_07_PP.csv',
 'MERGED2009_10_PP.csv',
 'MERGED2003_04_PP.csv',
 'MERGED1998_99_PP.csv',
 'MERGED2012_13_PP.csv',
 'MERGED2019_20_PP.csv',
 'MERGED2011_12_PP.csv',
 'MERGED2014_15_PP.csv',
 'MERGED2000_01_PP.csv',
 'MERGED2007_08_PP.csv',
 'MERGED2016_17_PP.csv',
 'MERGED2018_19_PP.csv',
 'MERGED2008_09_PP.csv',
 'MERGED2002_03_PP.csv',
 'MERGED2004_05_PP.csv',
 'MERGED2010_11_PP.csv',
 'MERGED2013_14_PP.csv',
 'MERGED2005_06_PP.csv',
 'MERGED1999_00_PP.csv',
 'MERGED2015_16_PP.csv',
 'MERGED1996_97_PP.csv',
 'MERGED2017_18_PP.csv',
 'MERGED1997_98_PP.csv',
 'MERGED2020_21_PP.csv',
 'MERGED2001_02_PP.csv']

## Step 7 - Load data files
 
Now that you have a clean list of the yearly files, you want to loop through them and read them into a dataframe one at a time. You only load six columns: ["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"].

You should use "usecols" option of Pandas to avoid reading unwanted columns. You also want to add a new column call "YEAR" to differentiate the data frames from each other. The YEAR variable should be yyyy format so tht you can convert them into integer. If you use the format yyyy-yy (such as 1997-98 school year), you will not be able to convert them directly to integer. If you use scatter plot, the YEAR needs to be converted to integer or float. 

You would use an empty list and append the yearly dataframes to the list. After all data files are loaded and appended to the list, you would use Pandas to concatenate them into a new single data frame.

Note: this exercise incorporates many techques we learned before:

- list (creating an empty, append an item to the list)
- for loop 
- read only the needed columns from a file (using usecols option)
- add a new column to a data frame
- concatenate multiple dataframes into a single one

This exercise may appear challenging but it worths the effort. You will learn a lot and love it. I promise.

In [15]:
#(Write code here)
yearly_list.sort()

print("processing file", yearly_list[0])
df_all = pd.read_csv("/content/" + yearly_list[0], usecols=["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"])
df_all["year"] = yearly_list[0][6:10]
print(df_all.shape)

for yearly_file in yearly_list[1:]:
    print("processing file", yearly_file)
    df = pd.read_csv("/content/" + yearly_file, usecols=["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"])
    df["year"] = yearly_file[6:10]
    df_all = df_all.append(df, ignore_index = True)
    print(df_all.shape)

processing file MERGED1996_97_PP.csv
(7007, 7)
processing file MERGED1997_98_PP.csv
(13941, 7)
processing file MERGED1998_99_PP.csv
(20643, 7)
processing file MERGED1999_00_PP.csv
(27252, 7)
processing file MERGED2000_01_PP.csv
(33906, 7)
processing file MERGED2001_02_PP.csv
(40631, 7)
processing file MERGED2002_03_PP.csv
(47283, 7)
processing file MERGED2003_04_PP.csv
(53956, 7)
processing file MERGED2004_05_PP.csv
(60703, 7)
processing file MERGED2005_06_PP.csv
(67602, 7)
processing file MERGED2006_07_PP.csv
(74553, 7)
processing file MERGED2007_08_PP.csv
(81524, 7)
processing file MERGED2008_09_PP.csv
(88579, 7)
processing file MERGED2009_10_PP.csv
(95796, 7)
processing file MERGED2010_11_PP.csv
(103266, 7)
processing file MERGED2011_12_PP.csv
(111012, 7)
processing file MERGED2012_13_PP.csv
(118874, 7)
processing file MERGED2013_14_PP.csv
(126743, 7)
processing file MERGED2014_15_PP.csv
(134509, 7)
processing file MERGED2015_16_PP.csv
(142175, 7)
processing file MERGED2016_17_PP.csv
(149413, 7)
processing file MERGED2017_18_PP.csv
(156525, 7)
processing file MERGED2018_19_PP.csv
(163332, 7)
processing file MERGED2019_20_PP.csv
(170026, 7)
processing file MERGED2020_21_PP.csv
(176707, 7)

In [16]:
df_all.sample(10)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
154311,440873,Vatterott College-Dividend,TN,5.0,NaN,11068.0,2017
52417,369792,Windham Memorial Hospital-Radiologic Technolog...,CT,1.0,0.3800,NaN,2003
72576,369400,Universal Technical Institute-Auto Motorcycle ...,FL,5.0,NaN,NaN,2006
35029,141486,Chaminade University of Honolulu,HI,8.0,0.6966,12790.0,2001
100614,372772,Heritage Institute-Jacksonville,FL,5.0,NaN,NaN,2010
17694,207315,Oklahoma State University Center for Health Sc...,OK,6.0,NaN,NaN,1998
5453,240745,Guam Community College,GU,9.0,NaN,NaN,1996
50063,190169,Columbia-Greene Community College,NY,2.0,NaN,2592.0,2003
152510,214801,Pennsylvania State University-Penn State Abington,PA,2.0,0.8523,14516.0,2017
114877,226408,College of the Mainland,TX,6.0,NaN,1494.0,2012

## Step 8 - Explore the new dataframe 

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc.

In [17]:
df_all.shape #here is the shape of the dataframe we have 7 columns and 176707 rows

(176707, 7)

In [21]:
df_all.head(10) # Here are the top 10 observations

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
0,100636,Community College of the Air Force,AL,0.0,NaN,NaN,1996
1,100654,Alabama A & M University,AL,5.0,NaN,NaN,1996
2,100663,University of Alabama at Birmingham,AL,5.0,NaN,NaN,1996
3,100672,ALABAMA AVIATION AND TECHNICAL COLLEGE,AL,5.0,NaN,NaN,1996
4,100690,Amridge University,AL,5.0,NaN,NaN,1996
5,100706,University of Alabama in Huntsville,AL,5.0,NaN,NaN,1996
6,100724,Alabama State University,AL,5.0,NaN,NaN,1996
7,100751,The University of Alabama,AL,5.0,NaN,NaN,1996
8,100760,Central Alabama Community College,AL,5.0,NaN,NaN,1996
9,100812,Athens State University,AL,5.0,NaN,NaN,1996

In [22]:
df_all.tail(10) # Here are the bottom 10 observations

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
176697,49576714,Pennsylvania State University-Penn State New K...,PA,2.0,NaN,13720.0,2020
176698,49576715,Pennsylvania State University-Penn State Abington,PA,2.0,NaN,14542.0,2020
176699,49576716,Pennsylvania State University-Penn State Schuy...,PA,2.0,NaN,14486.0,2020
176700,49576717,Pennsylvania State University-Penn State Scranton,PA,2.0,NaN,14486.0,2020
176701,49576718,Pennsylvania State University-Penn State Shenango,PA,2.0,NaN,13360.0,2020
176702,49576719,Pennsylvania State University-Penn State Wilke...,PA,2.0,NaN,13604.0,2020
176703,49576720,Pennsylvania State University-Penn State York,PA,2.0,NaN,14486.0,2020
176704,49576721,Pennsylvania State University-Penn State Great...,PA,2.0,NaN,NaN,2020
176705,49576722,Pennsylvania State University-Penn State Harri...,PA,2.0,NaN,15216.0,2020
176706,49576723,Pennsylvania State University-Penn State Brand...,PA,2.0,NaN,14486.0,2020

In [23]:
df_all.sample(10) # here are the sample 10 values of the data frame

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
149916,125028,Ventura College,CA,8.0,NaN,1388.0,2017
136291,171128,Michigan Technological University,MI,3.0,0.7544,14286.0,2015
92480,222707,American Commercial College-Odessa,TX,6.0,NaN,NaN,2009
116921,444486,Paul Mitchell the School-Gastonia,NC,5.0,NaN,NaN,2012
161548,450128,Blue Cliff College-Alexandria,LA,5.0,NaN,NaN,2018
142784,129367,Capital Community College,CT,1.0,NaN,4236.0,2016
163593,112525,Western University of Health Sciences,CA,8.0,NaN,NaN,2019
25242,230588,SNOW COLLEGE-RICHFIELD CAMPUS,UT,7.0,NaN,NaN,1999
122697,227216,University of North Texas,TX,6.0,0.5969,8745.0,2013
36150,173559,Minnesota State Community and Technical College,MN,4.0,NaN,3191.0,2001

In [24]:
df_all.info() # column data types and non null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176707 entries, 0 to 176706
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   UNITID         176707 non-null  int64
 1   INSTNM         176707 non-null  object
 2   STABBR         176707 non-null  object
 3   REGION         176706 non-null  float64
 4   ADM_RATE       48863 non-null   float64
 5   TUITIONFEE_IN  86867 non-null   float64
 6   year           176707 non-null  object
dtypes: float64(3), int64(1), object(3)
memory usage: 9.4+ MB

In [26]:
df_all.isnull() # null values

        UNITID  INSTNM  STABBR  REGION  ADM_RATE  TUITIONFEE_IN   year
0        False   False   False   False      True           True  False
1        False   False   False   False      True           True  False
2        False   False   False   False      True           True  False
3        False   False   False   False      True           True  False
4        False   False   False   False      True           True  False
...        ...     ...     ...     ...       ...            ...    ...
176702   False   False   False   False      True          False  False
176703   False   False   False   False      True          False  False
176704   False   False   False   False      True           True  False
176705   False   False   False   False      True          False  False
176706   False   False   False   False      True          False  False

[176707 rows x 7 columns]

In [27]:
df_all.describe() #statistics

             UNITID         REGION      ADM_RATE  TUITIONFEE_IN
count  1.767070e+05  176706.000000  48863.000000   86867.000000
mean   1.054338e+06       4.559279      0.693785   12037.588290
std    4.959072e+06       2.188341      0.217019   10462.970227
min    1.006360e+05       0.000000      0.000000       0.000000
25%    1.641730e+05       3.000000      0.556700    3936.000000
50%    2.136310e+05       5.000000      0.719500    9422.000000
75%    4.137780e+05       6.000000      0.857100   16490.000000
max    4.957672e+07       9.000000      1.000000   74787.000000

## Step 9 - UMBC 

The dataframe contains many years of data of all U.S. colleges. let's just look at UMBC. Filter/query the dataframe to retrieve only rows that belong to UMBC (one row represent one year). Save the UMNC data to a new data frame. using a new variable for the UMBC data frame, so that the old big data frame is still available for later use.

In [29]:
#(Write code here)
df=df_all.loc[df_all['INSTNM'] == "University of Maryland-Baltimore County"]
df

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000
35821,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001
42524,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002
49156,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003
55786,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005
69401,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006
76332,163268,University of Maryland-Baltimore County,MD,2.0,0.6895,8708.0,2007
83291,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008
90324,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009
97506,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010
104960,163268,University of Maryland-Baltimore County,MD,2.0,0.6081,9467.0,2011
112672,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012
120503,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013
128353,163268,University of Maryland-Baltimore County,MD,2.0,0.5961,10384.0,2014
136064,163268,University of Maryland-Baltimore County,MD,2.0,0.5942,11006.0,2015
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020

## Step 10 - Explore the new dataframe

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc

In [30]:
#(Write code here)
df.shape

(25, 7)

In [31]:
df.head(10)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000
35821,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001
42524,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002
49156,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003
55786,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005

In [32]:
df.tail(10)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
104960,163268,University of Maryland-Baltimore County,MD,2.0,0.6081,9467.0,2011
112672,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012
120503,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013
128353,163268,University of Maryland-Baltimore County,MD,2.0,0.5961,10384.0,2014
136064,163268,University of Maryland-Baltimore County,MD,2.0,0.5942,11006.0,2015
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020

In [33]:
df.sample(10)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
83291,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008
69401,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005
90324,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
97506,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 2151 to 171401
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   UNITID         25 non-null     int64
 1   INSTNM         25 non-null     object
 2   STABBR         25 non-null     object
 3   REGION         25 non-null     float64
 4   ADM_RATE       20 non-null     float64
 5   TUITIONFEE_IN  21 non-null     float64
 6   year           25 non-null     object
dtypes: float64(3), int64(1), object(3)
memory usage: 1.6+ KB

In [35]:
df.isnull()

        UNITID  INSTNM  STABBR  REGION  ADM_RATE  TUITIONFEE_IN   year
2151     False   False   False   False      True           True  False
9056     False   False   False   False      True           True  False
15923    False   False   False   False      True           True  False
22598    False   False   False   False      True           True  False
29178    False   False   False   False      True          False  False
35821    False   False   False   False     False          False  False
42524    False   False   False   False     False          False  False
49156    False   False   False   False     False          False  False
55786    False   False   False   False     False          False  False
62522    False   False   False   False     False          False  False
69401    False   False   False   False     False          False  False
76332    False   False   False   False     False          False  False
83291    False   False   False   False     False          False  False
90324    False   False   False   False     False          False  False
97506    False   False   False   False     False          False  False
104960   False   False   False   False     False          False  False
112672   False   False   False   False     False          False  False
120503   False   False   False   False     False          False  False
128353   False   False   False   False     False          False  False
136064   False   False   False   False     False          False  False
143685   False   False   False   False     False          False  False
150891   False   False   False   False     False          False  False
157940   False   False   False   False     False          False  False
164723   False   False   False   False     False          False  False
171401   False   False   False   False     False          False  False

In [36]:
df.describe()

         UNITID  REGION   ADM_RATE  TUITIONFEE_IN
count      25.0    25.0  20.000000      21.000000
mean   163268.0     2.0   0.641880    9168.571429
std         0.0     0.0   0.051853    1854.082079
min    163268.0     2.0   0.568300    5490.000000
25%    163268.0     2.0   0.600600    8520.000000
50%    163268.0     2.0   0.632100    9171.000000
75%    163268.0     2.0   0.690825   10384.000000
max    163268.0     2.0   0.717400   12028.000000

## Step 11 - Plot UMBC's in-state tution overtime Bar Chart

In [42]:
#(Write code here)

barplt = px.bar(df, x='year', y='TUITIONFEE_IN')
barplt.show()

## Step 12 - Plot UMBC's in-state tution overtime using line Chart

In [43]:
#(Write code here)
Line_chrt = px.line(df, x="TUITIONFEE_IN", y="year")
Line_chrt.show()

## Step 13 - Tuition Growth Rate

Now let's look at the tuition growth rate year over year. We need to calculate UMBC tuition change percentage each year. First convert the TUITIONFEE_IN column to a Python List

In [48]:
#(Write code here)
list_con = df.TUITIONFEE_IN.tolist()
print(list_con)

[nan, nan, nan, nan, 5490.0, 5910.0, 6362.0, 7388.0, 8020.0, 8520.0, 8622.0, 8708.0, 8780.0, 8872.0, 9171.0, 9467.0, 9764.0, 10068.0, 10384.0, 11006.0, 11264.0, 11518.0, 11778.0, 12028.0, 9420.0]

## Step 14 - Loop through the list and calculate the % change each year over the prior year

This takes some effort. Not hard, just some abstract/logical thinking and some experiments. Have fun on this one.

In [52]:
 #(Write code here)
percentage_list = []
for i in range(0,len(list_con)):
  ptg=((list_con[i]-list_con[i-1])/list_con[i-1])*100
  percentage_list.append(ptg)
percentage_list

[nan,
 nan,
 nan,
 nan,
 nan,
 7.650273224043716,
 7.648054145516074,
 16.12700408676517,
 8.554412560909583,
 6.234413965087282,
 1.1971830985915493,
 0.9974483878450475,
 0.8268259072117593,
 1.0478359908883828,
 3.370153291253381,
 3.227565151019518,
 3.1372134783986483,
 3.11347808275297,
 3.1386571315057608,
 5.989984591679507,
 2.344175904052335,
 2.254971590909091,
 2.2573363431151243,
 2.122601460349805,
 -21.68274027269704]

## Step 15 - Round up the percentage to two decimal points

The resulting number has many decimal points which are unnecessary and not visually appealing. You can use for loop. Or better, use list comprehension for simplicity/brevity.

In [54]:
#(Write code here)
new_list = [round(i, 2) for i in percentage_list]
print(new_list)

[nan, nan, nan, nan, nan, 7.65, 7.65, 16.13, 8.55, 6.23, 1.2, 1.0, 0.83, 1.05, 3.37, 3.23, 3.14, 3.11, 3.14, 5.99, 2.34, 2.25, 2.26, 2.12, -21.68]

## Step 16 - Add the list of the percentages to the dataframe as a new column ("PCT_CHANGE")

Not as hard as you may think. If you get stuck, you think too hard. Google it and you will find the answer.

In [55]:
#(Write code here)
df['PCT_CHANGE'] = new_list
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year,PCT_CHANGE
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996,NaN
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997,NaN
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998,NaN
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999,NaN
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000,NaN
35821,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001,7.65
42524,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002,7.65
49156,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003,16.13
55786,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004,8.55
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005,6.23
69401,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006,1.20
76332,163268,University of Maryland-Baltimore County,MD,2.0,0.6895,8708.0,2007,1.00
83291,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008,0.83
90324,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009,1.05
97506,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010,3.37
104960,163268,University of Maryland-Baltimore County,MD,2.0,0.6081,9467.0,2011,3.23
112672,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012,3.14
120503,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013,3.11
128353,163268,University of Maryland-Baltimore County,MD,2.0,0.5961,10384.0,2014,3.14
136064,163268,University of Maryland-Baltimore County,MD,2.0,0.5942,11006.0,2015,5.99
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016,2.34
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017,2.25
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018,2.26
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019,2.12
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020,-21.68

## Step 17 - Finaly, we can make the plot tuition growth rate year over year - bar first, then line chart

In [56]:
# (write code here)

Bar_chart = px.bar(df, x="year", y="PCT_CHANGE")
Bar_chart.show()

In [57]:
line_chart = px.line(df, x="year", y="PCT_CHANGE")
line_chart.show()

## Step 18 - Define Growth Rate Function

Since we want to do the same calculation for JHU. Instead of doing it piecemeal as we did for UMBC. Let's create a function which can be reused for any college. This function takes a list of tuitions and return a list of percentage changes year over year. This function can be used later.

In [60]:
#(Write code here)



def growth_rate(lst):
  pct_ch_list=[]
  for i in range(0,len(lst)):
    pct_change=((lst[i]-lst[i-1])/lst[i-1])*100
    pct_ch_list.append(pct_change)
    pct_ch_rnd=[round(x,2) for x in pct_ch_list]  
  return pct_ch_rnd

## Step 19 - Get JHU Data

The dataframe contains many years of data of all U.S. colleges. Let's just look at JHU. Filter/query the dataframe to retrieve only rows that belong to JHU. Save the JHU data to a new data frame using a new variable so that the old big data frame is still available for later use.

In [61]:
#(Write code here)
df1=df_all.loc[df_all['INSTNM'] == "Johns Hopkins University"] 
df1

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
2139,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1996
9046,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1997
15914,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1998
22589,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1999
29169,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000
35812,162928,Johns Hopkins University,MD,2.0,0.3431,26210.0,2001
42515,162928,Johns Hopkins University,MD,2.0,0.3506,27390.0,2002
49148,162928,Johns Hopkins University,MD,2.0,0.3060,28730.0,2003
55779,162928,Johns Hopkins University,MD,2.0,0.3071,30140.0,2004
62515,162928,Johns Hopkins University,MD,2.0,0.3509,31620.0,2005
69394,162928,Johns Hopkins University,MD,2.0,0.2792,33900.0,2006
76325,162928,Johns Hopkins University,MD,2.0,0.2571,35900.0,2007
83284,162928,Johns Hopkins University,MD,2.0,0.2609,37700.0,2008
90317,162928,Johns Hopkins University,MD,2.0,0.2782,39150.0,2009
97499,162928,Johns Hopkins University,MD,2.0,0.2225,40680.0,2010
104953,162928,Johns Hopkins University,MD,2.0,0.1940,42280.0,2011
112665,162928,Johns Hopkins University,MD,2.0,0.1843,43390.0,2012
120496,162928,Johns Hopkins University,MD,2.0,0.1813,45470.0,2013
128346,162928,Johns Hopkins University,MD,2.0,0.1608,47060.0,2014
136057,162928,Johns Hopkins University,MD,2.0,0.1412,48710.0,2015
143678,162928,Johns Hopkins University,MD,2.0,0.1284,50410.0,2016
150886,162928,Johns Hopkins University,MD,2.0,0.1254,52170.0,2017
157935,162928,Johns Hopkins University,MD,2.0,0.1148,53740.0,2018
164718,162928,Johns Hopkins University,MD,2.0,0.1117,55350.0,2019
171396,162928,Johns Hopkins University,MD,2.0,0.1106,54160.0,2020

## Step 20 - Plot JHU's in-state tuition overtime

Let's plot bar and then line chart.

In [62]:
# <14> 
# Plot JHU's in-state tuition overtime from 1996 to 2019. 
# Let's plot bar and line chart together

#(Write code here)
jhu = df1.sort_values(by=["year"])
Bar_chrt = px.bar(jhu, x="year", y="TUITIONFEE_IN")
Bar_chrt.show()

In [63]:
line_chrt = px.line(jhu, x="year", y="TUITIONFEE_IN")
line_chrt.show()

## Step 21 - Calculate Tuition Growth Rate using the Function defined earlier

In [64]:
# Write code here
jhu_fee=jhu["TUITIONFEE_IN"].to_list()

jhu_pct_ch=growth_rate(jhu_fee)
jhu_pct_ch

[nan,
 nan,
 nan,
 nan,
 nan,
 5.13,
 4.5,
 4.89,
 4.91,
 4.91,
 7.21,
 5.9,
 5.01,
 3.85,
 3.91,
 3.93,
 2.63,
 4.79,
 3.5,
 3.51,
 3.49,
 3.49,
 3.01,
 3.0,
 -2.15]

## Step 22 - Add the list of percentage changes to the dataframe as a new column ("PCT_CHANGE")

In [65]:
#(Write code here)
df1['PCT_CHANGE'] = jhu_pct_ch
df1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year,PCT_CHANGE
2139,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1996,NaN
9046,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1997,NaN
15914,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1998,NaN
22589,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1999,NaN
29169,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000,NaN
35812,162928,Johns Hopkins University,MD,2.0,0.3431,26210.0,2001,5.13
42515,162928,Johns Hopkins University,MD,2.0,0.3506,27390.0,2002,4.50
49148,162928,Johns Hopkins University,MD,2.0,0.3060,28730.0,2003,4.89
55779,162928,Johns Hopkins University,MD,2.0,0.3071,30140.0,2004,4.91
62515,162928,Johns Hopkins University,MD,2.0,0.3509,31620.0,2005,4.91
69394,162928,Johns Hopkins University,MD,2.0,0.2792,33900.0,2006,7.21
76325,162928,Johns Hopkins University,MD,2.0,0.2571,35900.0,2007,5.90
83284,162928,Johns Hopkins University,MD,2.0,0.2609,37700.0,2008,5.01
90317,162928,Johns Hopkins University,MD,2.0,0.2782,39150.0,2009,3.85
97499,162928,Johns Hopkins University,MD,2.0,0.2225,40680.0,2010,3.91
104953,162928,Johns Hopkins University,MD,2.0,0.1940,42280.0,2011,3.93
112665,162928,Johns Hopkins University,MD,2.0,0.1843,43390.0,2012,2.63
120496,162928,Johns Hopkins University,MD,2.0,0.1813,45470.0,2013,4.79
128346,162928,Johns Hopkins University,MD,2.0,0.1608,47060.0,2014,3.50
136057,162928,Johns Hopkins University,MD,2.0,0.1412,48710.0,2015,3.51
143678,162928,Johns Hopkins University,MD,2.0,0.1284,50410.0,2016,3.49
150886,162928,Johns Hopkins University,MD,2.0,0.1254,52170.0,2017,3.49
157935,162928,Johns Hopkins University,MD,2.0,0.1148,53740.0,2018,3.01
164718,162928,Johns Hopkins University,MD,2.0,0.1117,55350.0,2019,3.00
171396,162928,Johns Hopkins University,MD,2.0,0.1106,54160.0,2020,-2.15

## Step 23 - Plot the JHU percentage changes tuitions over time

Bar plot first, then line plot.

In [67]:
#(Write code here)
Bar_chrt= px.bar(df1, x='year', y='PCT_CHANGE')
Bar_chrt.show()

In [69]:
line_chrt = px.line(df1, y="PCT_CHANGE", x="year",)
line_chrt.show()

## Step 24 - Compare UMBC and JHU 

In order to plot both UMBC and JHU tuition change over time in the same plot, we need to combine the two datasets using the common key of YEAR. 

First make a umbc2 dataframe with only two columns needed. We don't need other columns. Also change the column name from "PCT_CHANGE" to "UMBC_PCT" in preparation for the merge. This is because both umbc and jhu dataframe have the same column name "PCT_CHANGE", we rename them to there is no collision during the merge. BTW, Pandas handles collision gracefully, Feel free to try it without changing the column names.

In [70]:
#(Write code here)
umbc2 = df[['PCT_CHANGE', 'year']]
umbc2.rename(columns = {'PCT_CHANGE': 'UMBC_PCT'}, inplace=True)
umbc2.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       UMBC_PCT  year
2151        NaN  1996
9056        NaN  1997
15923       NaN  1998
22598       NaN  1999
29178       NaN  2000

## Step 25 

Then make a jhu2 dataframe with only two columns needed. WE don't need other columns. Also change the column name from "PCT_CHANGE" to "JHU_PCT"  in preparation for the merge

In [71]:
#(Write code here)
jhu2= df1[['PCT_CHANGE', 'year']]
jhu2.rename(columns = {'PCT_CHANGE': 'JHU_PCT'}, inplace=True)
jhu2.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       JHU_PCT  year
2139       NaN  1996
9046       NaN  1997
15914      NaN  1998
22589      NaN  1999
29169      NaN  2000

## Step 26 - Merger the two data frames and display the new dataframe

In [72]:
#(Write code here)
df2=pd.merge(umbc2, jhu2, left_on='year', right_on='year', how='inner')
df2

    UMBC_PCT  year  JHU_PCT
0        NaN  1996      NaN
1        NaN  1997      NaN
2        NaN  1998      NaN
3        NaN  1999      NaN
4        NaN  2000      NaN
5       7.65  2001     5.13
6       7.65  2002     4.50
7      16.13  2003     4.89
8       8.55  2004     4.91
9       6.23  2005     4.91
10      1.20  2006     7.21
11      1.00  2007     5.90
12      0.83  2008     5.01
13      1.05  2009     3.85
14      3.37  2010     3.91
15      3.23  2011     3.93
16      3.14  2012     2.63
17      3.11  2013     4.79
18      3.14  2014     3.50
19      5.99  2015     3.51
20      2.34  2016     3.49
21      2.25  2017     3.49
22      2.26  2018     3.01
23      2.12  2019     3.00
24    -21.68  2020    -2.15

## Step 27 - Plot UMBC and JHU separately on the same line plot

In [73]:

line_plt = px.line(df2, x="year", y=["UMBC_PCT","JHU_PCT"])
line_plt.show()

## Step 28 - Document your observation of the comparison plots using the following Markdown cell

from 2001-02 the fee structures for both umbc and jhu are same. There is a huge increase and decrease in fee of umbc over 2002-02, however the fee of jhu remained the same. There are slight inflations and deflations in both the fee structures of umbc and jhu in between 2005-2019. There is a huge decrease in the fee of umbc in 2020.